name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platypus-interactive/github-profile-readme-snake@v1
        id: snake_generator
        with:
          github_user_name: ${{ github.repository_owner }}
          # The following options are customizable:
          # snake_animation_duration: 500 # Default is 500 (milliseconds)
          # snake_animation_frame_delay: 20 # Default is 20 (milliseconds)
          # snake_animation_path: ./assets/snake.svg # Default is ./assets/snake.svg
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Not usually needed unless you hit API rate limits

      - name: Push to repo
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Generate Snake Animation" || echo "No changes to commit"
          git push
